name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: Build and Test
        run: mvn -B package --file pom.xml
  package-release:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: mvn -B package --file pom.xml
      - name: Determine Release Name
        run: "echo '::set-output name=name::build-'$(date +%Y-%m-%d-%H%M)" #$(date +%Y%m%d-%H%M%S) #$(git rev-parse HEAD | cut -c 1-8) #LATEST #$(basename "${{ github.ref }}")
        id: release-name